version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.9
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
