overrides:
- files: 'src/**/__tests__/*.{js,ts}'
  env:
    jest: true
  rules:
    '@typescript-eslint/no-explicit-any': off

extends:
- eslint:recommended
- plugin:@typescript-eslint/recommended
- plugin:prettier/recommended
- prettier/@typescript-eslint

parser: '@typescript-eslint/parser'

env:
  shared-node-browser: true
  es6: true

parserOptions:
  sourceType: module

rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-explicit-any': off
